version: "3.7"
services:
  #Database
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - webappnetwork
    command: mongod --port 27017
  #API (Sails.js)
  api:
    image: mhart/alpine-node
    restart: always
    ports:
      - "1337:1337"
    volumes:
      - ./api:/api
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - webappnetwork
    build: ./api
    command: sails lift
    environment:
      WAIT_HOSTS: mongodb:27017
  #Frontend (React)
  client:
    image: mhart/alpine-node
    restart: always
    ports:
      - "3000:3000"
    working_dir: /client/src/app
    volumes:
      - ./client:/client/src/app
    entrypoint: ["npm", "start"]
    links:
      - api
    networks:
      - webappnetwork
    build: ./client
networks:
  webappnetwork:
    driver: bridge