version: "3.7"
services:
  #Database
# Uncomment when ready to hook API to a MongoDB
# Also uncomment the api "depends_on" value as well as the "dbdata" volume
#  mongodb:
#    image: mongo
#    container_name: mongodb
#    ports:
#      - "27017:27017"
#    networks:
#      - webappnetwork
#    volumes:
#      - dbdata:/data/db
#    command: mongod --port 27017 --logpath=/dev/null
  #API (Sails.js)
  api:
    image: mhart/alpine-node
    ports:
      - "1337:1337"
    volumes:
      - ./api:/api
    #depends_on:
      #- mongodb
    networks:
      - webappnetwork
    build: ./api
    command: node app.js
  #Frontend (React)
  client:
    image: mhart/alpine-node
    ports:
      - "3000:3000"
    working_dir: /client/src/app
    volumes:
      - ./client:/client/src/app
    depends_on:
      - api
    entrypoint: ["npm", "start"]
    networks:
      - webappnetwork
    build: ./client
networks:
  webappnetwork:
    driver: bridge
#volumes:
  #dbdata: